import { AVATAR_CODE, AVATAR_GROUP_CODE, AVATAR_IMG_CODE, AVATAR_LINK_CODE, AVATAR_WRAPPER_CODE } from './avatar';
import { AVATAR_GROUP_USAGE_CODE, AVATAR_LINK_USAGE_CODE, AVATAR_USAGE_CODE } from './usage';

export {
    AVATAR_CODE,
    AVATAR_WRAPPER_CODE,
    AVATAR_LINK_CODE,
    AVATAR_IMG_CODE,
    AVATAR_GROUP_CODE,
    AVATAR_USAGE_CODE,
    AVATAR_LINK_USAGE_CODE,
    AVATAR_GROUP_USAGE_CODE,
};
