import {
    MODAL_CLOSE_CODE,
    MODAL_CODE,
    MODAL_CONTENT_CODE,
    MODAL_LAYER_CODE,
    MODAL_TRIGGER_CODE,
    MODAL_WRAPPER_CODE,
} from './modal';
import { MODAL_USAGE_CODE } from './usage';

export {
    MODAL_CODE,
    MODAL_WRAPPER_CODE,
    MODAL_TRIGGER_CODE,
    MODAL_CONTENT_CODE,
    MODAL_LAYER_CODE,
    MODAL_CLOSE_CODE,
    MODAL_USAGE_CODE,
};
