export const PATHS = {
    HOME: '/',
    DOCUMENTATION: '/documentation',
    NOT_FOUND: '*',
    PAGES: {
        COMPONENTS: {
            ACCORDION: '/accordion',
            ALERT: '/alert',
            AVATAR: '/avatar',
            BADGE: '/badge',
            BLOCKQUOTE: '/blockquote',
            BREADCRUMB: '/breadcrumb',
            BTN: '/button',
            CARD: '/card',
            CHECKBOX: '/checkbox',
            DROPDOWN: '/dropdown',
            INPUT: '/input',
            INPUT_PASSWORD: '/input-password',
            LABEL: '/label',
            LOADER: '/loader',
            MODAL: '/modal',
            PAGINATION: '/pagination',
            PIN_INPUT: '/pin-input',
            PROGRESS: '/progress',
            RADIO: '/radio',
            REORDER: '/reorder',
            SELECT: '/select',
            SEPARATOR: '/separator',
            SIMPLE_LINK: '/simple-link',
            SWITCH: '/switch',
            TABS: '/tabs',
            TEXT: '/text',
            TEXTAREA: '/textarea',
            TITLE: '/title',
            TOAST: '/toast',
            TOOLTIP: '/tooltip',
        },
        DATA_FETCHING: {
            REACT_QUERY: '/react-query',
            RTK_QUERY: '/RTK-query',
        },
        FORM_VALIDATION: {
            YUP: '/yup',
            ZOD: '/zod',
        },
        STORE: {
            REDUX_TOOLKIT: '/redux-toolkit',
            ZUSTAND: '/zustand',
        },
    },
};
