export const PATHS = {
    HOME: '/',
    DOCUMENTATION: '/documentation',
    NOT_FOUND: '*',
    PAGES: {
        COMPONENTS: {
            ACCORDION: { path: '/accordion', isNew: false },
            ALERT: { path: '/alert', isNew: false },
            AVATAR: { path: '/avatar', isNew: false },
            BADGE: { path: '/badge', isNew: false },
            BLOCKQUOTE: { path: '/blockquote', isNew: false },
            BREADCRUMB: { path: '/breadcrumb', isNew: false },
            BTN: { path: '/button', isNew: false },
            CARD: { path: '/card', isNew: false },
            CAROUSEL: { path: '/carousel', isNew: true },
            CHECKBOX: { path: '/checkbox', isNew: false },
            DROPDOWN: { path: '/dropdown', isNew: true },
            INPUT: { path: '/input', isNew: false },
            INPUT_PASSWORD: { path: '/input-password', isNew: false },
            LABEL: { path: '/label', isNew: false },
            LOADER: { path: '/loader', isNew: false },
            MODAL: { path: '/modal', isNew: false },
            PAGINATION: { path: '/pagination', isNew: false },
            PIN_INPUT: { path: '/pin-input', isNew: false },
            PROGRESS: { path: '/progress', isNew: false },
            RADIO: { path: '/radio', isNew: false },
            REORDER: { path: '/reorder', isNew: false },
            SELECT: { path: '/select', isNew: true },
            SEPARATOR: { path: '/separator', isNew: false },
            SIMPLE_LINK: { path: '/simple-link', isNew: false },
            SWITCH: { path: '/switch', isNew: false },
            TABS: { path: '/tabs', isNew: false },
            TEXT: { path: '/text', isNew: false },
            TEXTAREA: { path: '/textarea', isNew: false },
            TITLE: { path: '/title', isNew: false },
            TOAST: { path: '/toast', isNew: false },
            TOOLTIP: { path: '/tooltip', isNew: false },
        },
        DATA_FETCHING: {
            RTK_QUERY: { path: '/RTK-query', isNew: false },
            TANSTACK_QUERY: { path: '/tanStack-query', isNew: false },
        },
        FORM_VALIDATION: {
            YUP: { path: '/yup', isNew: false },
            ZOD: { path: '/zod', isNew: false },
        },
        STORE: {
            REDUX_TOOLKIT: { path: '/redux-toolkit', isNew: false },
            ZUSTAND: { path: '/zustand', isNew: false },
        },
    },
};
