import { ReactNode } from 'react';
import type { Metadata } from 'next';
import { RootProvider } from '@providers';
import { Root, RootLayout, RootMain } from '@root';
import './globals.css';

export const metadata: Metadata = {
    title: {
        default: 'Next Template | Home Page',
        template: 'Next Template | %s',
    },
    description: 'Generated by Dmytro Rogkov',
};

type Props = {
    children: ReactNode;
};

export default function HomeLayout({ children }: Props) {
    return (
        <Root>
            <RootProvider>
                <RootLayout>
                    <RootMain>{children}</RootMain>
                </RootLayout>
            </RootProvider>
        </Root>
    );
}
