import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Next Template | Home Page',
    description: 'Generated by Dmytro Rogkov',
};

type Props = {
    children: React.ReactNode;
};

const RootLayout: React.FC<Props> = ({ children }) => {
    return (
        <html lang='en'>
            <body>
                <main>{children}</main>
            </body>
        </html>
    );
};

export default RootLayout;
