import {
    PAGINATION_CODE,
    PAGINATION_WRAPPER_CODE,
    PAGINATION_PREVIOUS_CODE,
    PAGINATION_ITEM_CODE,
    PAGINATION_NEXT_CODE,
    PAGINATION_ELLIPSIS_CODE,
    PAGINATION_HOOK_CODE,
    PAGINATION_UTILS_CODE,
} from './code';
import { PAGINATION_DEMO_CODE } from './demo';
import { PAGINATION_USAGE_CODE, PAGINATION_DATA_USAGE_CODE } from './usage';

export {
    PAGINATION_CODE,
    PAGINATION_WRAPPER_CODE,
    PAGINATION_PREVIOUS_CODE,
    PAGINATION_ITEM_CODE,
    PAGINATION_NEXT_CODE,
    PAGINATION_ELLIPSIS_CODE,
    PAGINATION_HOOK_CODE,
    PAGINATION_UTILS_CODE,
    PAGINATION_DEMO_CODE,
    PAGINATION_USAGE_CODE,
    PAGINATION_DATA_USAGE_CODE,
};
