import { TEXTAREA_CODE } from './code';
import { TEXTAREA_DEMO_CODE } from './demo';
import { TEXTAREA_USAGE_CODE, TEXTAREA_CONTROLLED_USAGE_CODE } from './usage';

export { TEXTAREA_CODE, TEXTAREA_DEMO_CODE, TEXTAREA_USAGE_CODE, TEXTAREA_CONTROLLED_USAGE_CODE };
