import { TABS_CODE, TABS_WRAPPER_CODE, TABS_LIST_CODE, TABS_TAB_CODE, TABS_PANELS_CODE, TABS_PANEL_CODE } from './code';
import { TABS_DEMO_CODE } from './demo';
import { TABS_USAGE_CODE, TABS_ACTIVE_USAGE_CODE, TABS_ANIMATION_USAGE_CODE } from './usage';

export {
    TABS_CODE,
    TABS_WRAPPER_CODE,
    TABS_LIST_CODE,
    TABS_TAB_CODE,
    TABS_PANELS_CODE,
    TABS_PANEL_CODE,
    TABS_DEMO_CODE,
    TABS_USAGE_CODE,
    TABS_ACTIVE_USAGE_CODE,
    TABS_ANIMATION_USAGE_CODE,
};
