import { TEXTAREA_CODE } from './textarea';
import { TEXTAREA_USAGE_CODE, TEXTAREA_CONTROLLING_USAGE_CODE } from './usage';

export { TEXTAREA_CODE, TEXTAREA_USAGE_CODE, TEXTAREA_CONTROLLING_USAGE_CODE };
