import { TOOLTIP_CODE, TOOLTIP_WRAPPER_CODE, TOOLTIP_TRIGGER_CODE, TOOLTIP_CONTENT_CODE } from './code';
import { TOOLTIP_DEMO_CODE } from './demo';
import { TOOLTIP_USAGE_CODE } from './usage';

export {
    TOOLTIP_CODE,
    TOOLTIP_WRAPPER_CODE,
    TOOLTIP_TRIGGER_CODE,
    TOOLTIP_CONTENT_CODE,
    TOOLTIP_DEMO_CODE,
    TOOLTIP_USAGE_CODE,
};
